### PR TITLE
Fix windows build

### PR DESCRIPTION
**Pull request by ngonkalves**
I wasn't able to build the project in windows, so I fixed it.

### CODE REVIEW

**Comment by Andrei-Straut** [comment]
Weird, my dev machine is windows, and I had no problem with the build process.
Weird case of "works on my machine?" :)

I will review and merge later during the day. 
Thanks! 👍

**Comment by Andrei-Straut** [comment]
@ngonkalves merge done, build passing 👍
https://www.andreistraut.info/jenkins/job/statkins-master/106/console

Npm complains about some package vulnerabilities though, I will review this later

**Comment by ngonkalves** [comment]
## Found 2 issues:
1. On windows the task "frontend-maven-plugin:1.6:npm (npm install)" is looking for nodejs in "X:\<instalation_dir>\node\node.exe" but this folder naming changed in some version to "X:\<instalation_dir>\nodejs\node.exe"
     - to overcome this I had to change frontend-maven-plugin configuration to download nodejs and npm from web and install it locally

2. Compilation issues on "ng build --prod --aot"
     -  fixed with preserveSymlinks: true in .angular-cli.json

## See error below:

[INFO] --- frontend-maven-plugin:1.6:npm (prod) @ statkins ---
[INFO] Running 'npm run-script build-prod' in T:\tmp\statkins\src\main\webapp
[INFO]
[INFO] > statkins@0.0.0 build-prod T:\tmp\statkins\src\main\webapp
[INFO] > ng build --prod --aot
[INFO]
[INFO] Date: 2018-05-21T08:12:47.575Z
[INFO] Hash: e1d9a8508564bb333b69
[INFO] Time: 15794ms
[INFO] chunk {scripts} scripts.4efc89ec27628b0eb07c.bundle.js (scripts) 758 kB [initial] [rendered]
[INFO] chunk {0}  (styles) [initial] [rendered]
[ERROR]
[INFO] chunk {1} polyfills.052d4761314902556e2b.bundle.js (polyfills) 610 bytes [initial] [rendered]
[ERROR] ERROR in T:/temp/statkins/src/main/webapp/src/main.ts
[INFO] chunk {2} main.0f27b8bd6b5585ab30f0.bundle.js (main) 605 bytes [initial] [rendered]
[INFO] chunk {3} inline.318b50c57b4eba3d437b.bundle.js (inline) 796 bytes [entry] [rendered]
[ERROR] Module build failed: Error: T:\temp\statkins\src\main\webapp\src\main.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
[ERROR]     at AngularCompilerPlugin.getCompiledFile (T:\temp\statkins\src\main\webapp\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
[ERROR]     at plugin.done.then (T:\temp\statkins\src\main\webapp\node_modules\@ngtools\webpack\src\loader.js:467:39)
[ERROR]     at <anonymous>
[ERROR] ERROR in T:/temp/statkins/src/main/webapp/src/polyfills.ts
[ERROR] Module build failed: Error: T:\temp\statkins\src\main\webapp\src\polyfills.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
[ERROR]     at AngularCompilerPlugin.getCompiledFile (T:\temp\statkins\src\main\webapp\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
[ERROR]     at plugin.done.then (T:\temp\statkins\src\main\webapp\node_modules\@ngtools\webpack\src\loader.js:467:39)
[ERROR]     at <anonymous>
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! statkins@0.0.0 build-prod: `ng build --prod --aot`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR!
[ERROR] npm ERR! Failed at the statkins@0.0.0 build-prod script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR]
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     C:\Users\ngoncalv\AppData\Roaming\npm-cache\_logs\2018-05-21T08_12_47_628Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:27 min
[INFO] Finished at: 2018-05-21T09:12:47+01:00

**Comment by Andrei-Straut** [comment]
@ngonkalves Open another pull request for your changes whenever you have the chance, happy to integrate it

**Pull request merged**
